## Applies the project's custom cursor textures globally and offers an
## accessibility opt-out. Autoload as "CursorState".
##
## Two textures are pre-generated by tools/generate_cursor_set.py:
##   - cursor_default.png  → bound to CURSOR_ARROW
##   - cursor_interact.png → bound to CURSOR_POINTING_HAND
##
## Any Control with `mouse_default_cursor_shape = CURSOR_POINTING_HAND`
## (every Button + every actionable Socket) therefore automatically
## swaps to the interact variant on hover, with no per-node wiring.
##
## Players who rely on OS cursor scaling / contrast can flip
## SettingsState.use_system_cursor and the engine reverts to the
## platform default.
extends Node

const DEFAULT_PATH := "res://art/cursors/cursor_default.png"
const INTERACT_PATH := "res://art/cursors/cursor_interact.png"
## Hotspot in the 28x28 canvas — coincides with the arrow tip baked
## into tools/generate_cursor_set.py (TIP = (2, 2) after downsample).
const HOTSPOT := Vector2(2, 2)

var _default_tex: Texture2D
var _interact_tex: Texture2D

func _ready() -> void:
	_default_tex = load(DEFAULT_PATH)
	_interact_tex = load(INTERACT_PATH)
	if SettingsState:
		SettingsState.use_system_cursor_changed.connect(_on_use_system_cursor_changed)
	_apply()

func _on_use_system_cursor_changed(_value: bool) -> void:
	_apply()

func _apply() -> void:
	if SettingsState and SettingsState.use_system_cursor:
		# Hand the cursor back to the OS for accessibility users — pass
		# null to clear each previously-set shape.
		Input.set_custom_mouse_cursor(null, Input.CURSOR_ARROW)
		Input.set_custom_mouse_cursor(null, Input.CURSOR_POINTING_HAND)
		return
	Input.set_custom_mouse_cursor(_default_tex, Input.CURSOR_ARROW, HOTSPOT)
	Input.set_custom_mouse_cursor(_interact_tex, Input.CURSOR_POINTING_HAND, HOTSPOT)
