#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "rembg[cpu]>=2.0.59",
#   "pillow>=10.0",
# ]
# ///
"""
Take an RGB PNG generated by mflux and write it back as an RGBA PNG with the
background cut out using rembg / isnet-general-use. Used to turn flat-BG
prop renders (switchboard panel, cable, etc.) into stackable layers.

Usage:
    tools/cutout.py <input.png> [output.png]

If output is omitted, the input is overwritten in place.
"""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image
from rembg import new_session, remove


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 1

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else src

    if not src.exists():
        print(f"cutout: input not found: {src}", file=sys.stderr)
        return 1

    # isnet-general-use is the best generic matter for non-photo / illustrated
    # subjects in our experience; u2net tends to leave halos on flat color
    # fills like our teal background.
    session = new_session("isnet-general-use")
    with Image.open(src) as img:
        cut = remove(img.convert("RGBA"), session=session)
    cut.save(dst, format="PNG")
    print(f"cutout: wrote {dst} ({cut.size[0]}x{cut.size[1]} RGBA)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
